"""
AI provider abstraction layer.

This module is intentionally kept as a pure-stdlib / third-party leaf — it
imports nothing from app.* — because core/config.py imports ProviderType from
here. Introducing any app.* import would create a circular dependency.
"""
from __future__ import annotations

import json
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional


class ProviderType(str, Enum):
    PLACEHOLDER = "placeholder"
    OPENAI = "openai"
    ANTHROPIC = "anthropic"


@dataclass
class ProviderConfig:
    provider_type: ProviderType
    openai_api_key: Optional[str] = field(default=None)
    anthropic_api_key: Optional[str] = field(default=None)
    model: str = field(default="claude-sonnet-4-6")


class AIProvider(ABC):
    @abstractmethod
    async def complete(self, prompt: str, **kwargs: object) -> str:
        """Send a prompt and return the raw text response."""

    @property
    @abstractmethod
    def provider_name(self) -> str:
        """Human-readable name of this provider."""


class PlaceholderProvider(AIProvider):
    """
    Returns structurally valid placeholder metadata derived from the prompt.

    Satisfies MetadataGenerateResponse validators:
    - title: 50-70 characters
    - description: ≥ 100 characters
    - tags: 8-15 unique items

    Unlike a static constant, this provider extracts a short excerpt from the
    incoming prompt so that each unique transcript produces visibly different
    output — making it easy to confirm the correct input flows through during
    development.

    Used when AI_PROVIDER=placeholder (default for local development).
    To get real AI-generated metadata set AI_PROVIDER=anthropic or
    AI_PROVIDER=openai and supply the corresponding API key in .env.
    """

    @property
    def provider_name(self) -> str:
        return "placeholder"

    @staticmethod
    def _excerpt(prompt: str, max_chars: int = 120) -> str:
        """Pull the first meaningful sentence from the prompt for use in the response."""
        # The prompt contains the transcript after a known header line.
        # Grab whatever text comes after "TRANSCRIPT:" up to the first newline.
        marker = "TRANSCRIPT:"
        idx = prompt.find(marker)
        source = prompt[idx + len(marker):].strip() if idx != -1 else prompt
        first_line = source.split("\n")[0].strip()
        excerpt = first_line[:max_chars]
        return excerpt if excerpt else source[:max_chars]

    async def complete(self, prompt: str, **kwargs: object) -> str:
        excerpt = self._excerpt(prompt)

        # Build a title that is guaranteed to be 50-70 chars.
        base_title = f"[DEV] {excerpt}"
        if len(base_title) > 70:
            base_title = base_title[:67] + "..."
        while len(base_title) < 50:
            base_title += " — Overview"
        title = base_title[:70]

        description = (
            f"[Placeholder response — configure AI_PROVIDER in .env for real metadata]\n\n"
            f"Transcript excerpt: {excerpt}\n\n"
            "This placeholder is generated by PlaceholderProvider and reflects the actual "
            "transcript submitted. Each unique transcript will produce a different excerpt "
            "here, confirming that the full request pipeline is wired correctly end-to-end.\n\n"
            "To generate real metadata:\n"
            "  1. Set AI_PROVIDER=anthropic (or openai) in backend/.env\n"
            "  2. Add the corresponding ANTHROPIC_API_KEY or OPENAI_API_KEY\n"
            "  3. Restart the backend server"
        )

        return json.dumps({
            "title": title,
            "description": description,
            "tags": [
                "placeholder metadata",
                "dev mode",
                "tubeflow",
                "metadata engine",
                "youtube seo",
                "ai generated",
                "content creator",
                "video metadata",
            ],
        })


class OpenAIProvider(AIProvider):
    """
    Calls the OpenAI Chat Completions API using the official async SDK.

    Model: gpt-4o-mini — fast, cheap, and sufficient for structured metadata
    generation where the prompt already constrains the output format tightly.

    The full metadata prompt is passed as the user message. A brief system
    message reinforces the JSON-only contract so the model does not add prose.
    """

    _MODEL = "gpt-4o-mini"
    _SYSTEM_MESSAGE = (
        "You are a YouTube metadata specialist. "
        "Respond ONLY with a valid JSON object — no markdown, no code fences, "
        "no commentary before or after the JSON."
    )

    def __init__(self, api_key: str) -> None:
        try:
            from openai import AsyncOpenAI  # local import keeps module loadable without openai installed
        except ImportError as exc:
            raise RuntimeError(
                "openai package is not installed. Run: pip install 'openai>=1.30.0'"
            ) from exc
        self._client = AsyncOpenAI(api_key=api_key)

    @property
    def provider_name(self) -> str:
        return f"openai/{self._MODEL}"

    async def complete(self, prompt: str, **kwargs: object) -> str:
        system_override: Optional[str] = kwargs.get("system", None)  # type: ignore[assignment]
        active_system = system_override if system_override is not None else self._SYSTEM_MESSAGE
        response = await self._client.chat.completions.create(
            model=self._MODEL,
            messages=[
                {"role": "system", "content": active_system},
                {"role": "user", "content": prompt},
            ],
            temperature=0.7,
            max_tokens=1024,
            response_format={"type": "json_object"},
        )
        content = response.choices[0].message.content
        return content if content is not None else ""


class AnthropicProvider(AIProvider):
    """
    Calls the Anthropic Messages API using the official async SDK.

    Supports vision: if `frames` (List[bytes] of JPEG data) are passed in
    kwargs, up to 3 are prepended as base64 image blocks before the text
    prompt, letting Claude see visual content alongside the transcript.
    """

    _SYSTEM_MESSAGE = (
        "You are a YouTube metadata specialist. "
        "Respond ONLY with a valid JSON object — no markdown, no code fences, "
        "no commentary before or after the JSON."
    )
    _MAX_FRAMES = 12

    def __init__(self, api_key: str, model: str = "claude-sonnet-4-6") -> None:
        self._api_key = api_key
        self._model = model

    @property
    def provider_name(self) -> str:
        return f"anthropic/{self._model}"

    async def complete(self, prompt: str, **kwargs: object) -> str:
        try:
            import anthropic  # local import keeps module loadable without anthropic installed
        except ImportError as exc:
            raise RuntimeError(
                "anthropic package is not installed. Run: pip install 'anthropic>=0.40.0'"
            ) from exc

        import base64
        from typing import List as _List

        frames: _List[bytes] = list(kwargs.get("frames", []))  # type: ignore[arg-type]
        system_override: Optional[str] = kwargs.get("system", None)  # type: ignore[assignment]
        active_system = system_override if system_override is not None else self._SYSTEM_MESSAGE

        # Evenly sample frames when more than _MAX_FRAMES are provided
        if len(frames) > self._MAX_FRAMES:
            step = len(frames) / self._MAX_FRAMES
            frames = [frames[int(i * step)] for i in range(self._MAX_FRAMES)]

        content: list[dict[str, object]] = []

        for frame_bytes in frames:
            b64 = base64.b64encode(frame_bytes).decode("utf-8")
            content.append(
                {
                    "type": "image",
                    "source": {
                        "type": "base64",
                        "media_type": "image/jpeg",
                        "data": b64,
                    },
                }
            )

        content.append({"type": "text", "text": prompt})

        client = anthropic.AsyncAnthropic(api_key=self._api_key)
        message = await client.messages.create(
            model=self._model,
            max_tokens=4096,
            system=active_system,
            messages=[{"role": "user", "content": content}],
        )

        for block in message.content:
            if block.type == "text":
                return block.text  # type: ignore[attr-defined]

        raise RuntimeError("Anthropic returned no text content in its response")


def create_provider(config: ProviderConfig) -> AIProvider:
    """Factory: instantiate the correct AIProvider from config."""
    if config.provider_type == ProviderType.PLACEHOLDER:
        return PlaceholderProvider()
    if config.provider_type == ProviderType.OPENAI:
        if not config.openai_api_key:
            raise ValueError(
                "AI_PROVIDER=openai requires OPENAI_API_KEY to be set in .env"
            )
        return OpenAIProvider(api_key=config.openai_api_key)
    if config.provider_type == ProviderType.ANTHROPIC:
        if not config.anthropic_api_key:
            raise ValueError(
                "AI_PROVIDER=anthropic requires ANTHROPIC_API_KEY to be set in .env"
            )
        return AnthropicProvider(api_key=config.anthropic_api_key, model=config.model)
    raise ValueError(f"Unknown provider type: {config.provider_type}")
